### ISSUE TITLE
LOVD won't install with error "Invalid default value for 'start_date'"

### ISSUE THREAD

**Issue by hypotheses** [LOVDnl/LOVD3#143]
Error during install while running query.
I ran:
CREATE TABLE lovd_announcements (
id SMALLINT(5) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
type VARCHAR(15) NOT NULL DEFAULT "information",
announcement TEXT NOT NULL,
start_date DATETIME NOT NULL DEFAULT "0000-00-00 00:00:00",
end_date DATETIME NOT NULL DEFAULT "9999-12-31 23:59:59",
lovd_read_only BOOLEAN NOT NULL DEFAULT 0,
created_by SMALLINT(5) UNSIGNED ZEROFILL,
created_date DATETIME NOT NULL,
edited_by SMALLINT(5) UNSIGNED ZEROFILL,
edited_date DATETIME,
PRIMARY KEY (id),
INDEX (created_by),
INDEX (edited_by),
CONSTRAINT lovd_announcements_fk_created_by FOREIGN KEY (created_by) REFERENCES lovd_users (id) ON DELETE SET NULL ON UPDATE CASCADE,
CONSTRAINT lovd_announcements_fk_edited_by FOREIGN KEY (edited_by) REFERENCES lovd_users (id) ON DELETE SET NULL ON UPDATE CASCADE)
ENGINE=InnoDB,
DEFAULT CHARACTER SET utf8

I got:
[42000] [1067] [Invalid default value for 'start_date']

I'm running mySQL Server version: 5.7.16-0ubuntu0.16.04.1 (Ubuntu)

**Comment by ifokkema** [comment]
Hi,

Thank you for your report. Could you check please if your SQL mode contains a `strict mode`? LOVD has been reported to misbehave quite a bit when one of the MySQL strict modes is enabled. So removing that setting in the MySQL settings would solve the problem most likely.

If you have direct access to the MySQL client, could you send me the output of:
```sql
SELECT @@sql_mode;
```

Otherwise, please check your my.cnf for the `sql-mode` setting. If you can't find it, it's set to its default, which includes a strict mode. In that case, please try to disable that mode and try again. We are still trying to make LOVD compatible with MySQL's strict modes.
More information in the [MySQL manual](http://dev.mysql.com/doc/refman/5.7/en/sql-mode.html) and a related issue: #144. If `ONLY_FULL_GROUP_BY` is also enabled, it should currently be disabled.

**Comment by hypotheses** [comment]
@ifokkema you were right about `strict` and `ONLY_FULL_GROUP_BY`

# manually entered setup.php mysql> select @@sql_mode;
+-------------------------------------------------------------------------------------------------------------------------------------------+
| @@sql_mode                                                                                                                                |
+-------------------------------------------------------------------------------------------------------------------------------------------+
| ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION |
+-------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

I'm not sure whether this is a good idea, but I tried
Change line 698 of install/inc-sql-tables.php to
    start_date DATETIME NOT NULL DEFAULT "1900-01-01 00:00:01",

Then the below errors showed up asking for default values for TEXT NOT NULL. 
# line 220, 221, 222: tissue, features, remarks are allowed to be NULL

By changing the above, the installation ran to finish. But then, 

"The requested URL /LOVD/setup was not found on this server." 
I installed LOVD in it's own directory within www-root folder. So, the current `url` is like this `https://10.0.2.2/LOVD/setup`

Not quite sure what is the issue here, however, by entering `setup.php` in the `url` I can open the page, but then all your tabs did not work as well `genes.php`, `transcripts.php`, etc.

**Comment by hypotheses** [comment]
I figured out the issues with pages with .php not loading properly.  
This problem came from that fact that I didn't move or didn't enable .htaccess file in the web-root yet.

**Comment by ifokkema** [comment]
Hi;

So now you have LOVD installed, but surely there will be more errors coming if `ONLY_FULL_GROUP_BY` and `STRICT_TRANS_TABLES` are not turned off, so I would recommend to disable these, until we find a way that LOVD can co-exist with these settings enabled.

**Comment by crowewe** [comment]
Hi, I running into similar problems installing build 18 (build 16 work is working). I got passed the "start_date" problem by adding:
#
# Changes for LOVD, 12/27/2016, WEC
# /etc/mysql/mysql.conf.d/mysqld.cnf
# https://github.com/LOVDnl/LOVD3/issues/144
# http://stackoverflow.com/questions/23921117/disable-only-full-group-by
sql_mode = "ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES"

but currently getting:

Error during install while running query.
I ran:

INSERT INTO lovd_diseases (symbol, name, created_by, created_date) VALUES ("Healthy/Control", "Healthy individual / control", 0, NOW())

I got:
[HY000] [1364] [Field 'tissues' doesn't have a default value]

A failed installation is most likely caused by a bug in LOVD.
Please file a bug and include the above messages to help us solve the problem.

Running under:
mysql  Ver 14.14 Distrib 5.7.16, for Linux (x86_64) using  EditLine wrapper
Oracle Virtual Box - Ubuntu 16LTS MATE

**Comment by ifokkema** [comment]
Hi,

> sql_mode = "ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES"

This actually enables the SQL modes that are problematic (but they're enabled by default already on that version of MySQL). It simply disables the other defaults. Could you try and remove the `STRICT_TRANS_TABLES` part or make it an empty string, then restart MySQL, and try again please? LOVD 3.0-18 should be compatible with the `ONLY_FULL_GROUP_BY` SQL mode, but `STRICT_TRANS_TABLES` is still causing issues.

> I do have LOVD running without problems under:
> LOVD v.3.0 Build 17
> mysql Ver 14.14 Distrib 5.5.53, for debian-linux-gnu (x86_64) using readline 6.3

That's correct, the problem indeed occurs only in later MySQL versions, that have enabled `STRICT_TRANS_TABLES` (enabled from 5.7.5 by default).

Please let me know if this helps!

**Comment by crowewe** [comment]
Hi Ivo,

Yes, replacing:
    sql_mode = "ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES"
with
   sql_mode = ""
in
  /etc/mysql/mysql.conf.d
solved the problem.

Look forward to customizing LOVD for somatic variants.

Thanks,

Bill
