### ISSUE TITLE
Created custom link is not displayed in variants table 

### ISSUE THREAD

**Issue by tsimakova** [LOVDnl/LOVD3#164]
I have created custom link (CFTR2_2016) and added this link to a new custom data column (CFTR2_2016). The link is active and displayed on the variant description form, however it is absent in the variants table (the field is blank). Plesae, see the [attached](https://drive.google.com/drive/folders/0B5GGg1fLQsySeTZmZmcyUkx2VWs?usp=sharing) files. What could be the problem?

**Comment by ifokkema** [comment]
Hi there,
Thank you for your report. Is this database online somewhere where we can reach it?

**Comment by tsimakova** [comment]
Hello,
you can find database at http://seqdb.parseq.pro/genes

**Comment by ifokkema** [comment]
Thank you for the link, I have investigated the issue and have found the problem.

In the definition of the custom link, there are two single quotes instead of one double quote, in this part:
`target=''_blank">`

This should be:
`target="_blank">`

If you replace those two single quotes by one double quote in the custom link definition, it will work as it should.

**Comment by tsimakova** [comment]
Now everything is ok, thanks. You can close this ticket.
