### ISSUE TITLE
SQL only full group by error in DBID check.

### ISSUE THREAD

**Issue by mkroon1** [LOVDnl/LOVD3#185]
Currently the selenium import tests fail on mysql 5.7.17 with default config while running a query to check a DBID. This looks to be a remnant of issue #161.

The faulty query is generated [here](https://github.com/LOVDnl/LOVD3/blob/b200c8bc53fdab28dbf85079f1705eeffa99ef69/src/inc-lib-form.php#L74-L103) and looks like this:
```sql
SELECT DISTINCT
  t.geneid,
  CONCAT(IFNULL(vog.`VariantOnGenome/DNA`, ""), ";", IFNULL(GROUP_CONCAT(vot.`VariantOnTranscript/DNA` SEPARATOR ";"), "")) AS variants,
  vog.`VariantOnGenome/DBID`
FROM lovd_v3_variants AS vog
  LEFT OUTER JOIN lovd_v3_variants_on_transcripts AS vot ON (vog.id = vot.id)
  LEFT OUTER JOIN lovd_v3_transcripts AS t ON (vot.transcriptid = t.id)
WHERE
  ((REPLACE(REPLACE(REPLACE(vog.`VariantOnGenome/DNA`, "(", ""), ")", ""), "?", "") = 'g.40702876G>T' AND vog.chromosome = '15')) AND
  BINARY vog.`VariantOnGenome/DBID` = 'IVD_000001' AND vog.id != '0000000002'
GROUP BY vog.id;
```

@ifokkema: as I understand it, the query is only used to check if there's one or more variants different from the current one (vog.id = '0000000002') that have the same DBID. So, can't we simplify it with something like what's below?

```sql
SELECT COUNT(*)
FROM lovd_v3_variants AS vog
  LEFT OUTER JOIN lovd_v3_variants_on_transcripts AS vot ON (vog.id = vot.id)
  LEFT OUTER JOIN lovd_v3_transcripts AS t ON (vot.transcriptid = t.id)
WHERE
  vog.`VariantOnGenome/DBID` = 'IVD_000001' AND vog.id != '0000000002';
```

**Comment by ifokkema** [comment]
Hi!

We can indeed definitely drop the data in the `SELECT`! It is needed to make a proper count, but since we don't actually use the count but just check if it's at least one, we can do with a normal `COUNT(*)` indeed.

The `WHERE` however, shouldn't be removed. This function doesn't check if simply this DBID exists, but if it exists with the same variant (but not this observation) as given. See the comments in the header of this function for its purpose. We might actually extend the `WHERE` to also check the vog position fields, if given. That'll speed up the query some more, I reckon?

**Comment by mkroon1** [comment]
PR #198 has a fix, simplifying the query by removing most from the select statement and group by statement.

> We might actually extend the WHERE to also check the vog position fields, if given. That'll speed up the query some more, I reckon?

I did not do this yet, as there are some corner cases to care about (e.g. null values for the position fields in either the query or the database) If this code needs to be improved performance-wise, I'd suggest to make a new issue.
