### ISSUE TITLE
Viewlist 'no results' warning message sometimes unclear.

### ISSUE THREAD

**Issue by mkroon1** [LOVDnl/LOVD3#189]
Viewlists generate a warning message ([see code here](https://github.com/LOVDnl/LOVD3/blob/c2b13d9934038f2d1489482c36889f9878590157/src/class/objects.php#L2438-L2450)) when there are no results for the given search conditions. Sometimes this message is unclear.

One example is PR #186:

> Note: the change in 4c910c9 moves the position fields settings for the viewlist into the VOG class definition. This causes the position fields to be ignored in the error message that appears when a region is specified for where there are no variants. E.g. `variants/chr21:1-2` will show a message like: `No variants found where chr is "21"!`

@ifokkema: do you know other examples where the error message doesn't make sense to the end-user?

**Comment by ifokkema** [comment]
There's a really annoying one, where various pages (I know at least LOVD+ has a page, but there are more as far as I remember) say:
`No custom_viewlists found!`
or
`No custom_viewlistmods found!`
(because the object name is used, and LOVD+ has a modified `custom_viewlist` object.

**Comment by ifokkema** [comment]
Turns out the code deliberately hides search terms on fields that are configured to be always hidden. I guess that makes sense when you're filtering variants in a view of variants within a certain screening or so, but in this case it's working against us. I guess we'll need to make a list of situation where we do and don't want the search terms hidden, and come up with a better plan :wink:
