### ISSUE TITLE
Import fails on column name containing `-`

### ISSUE THREAD

**Issue by mkroon1** [LOVDnl/LOVD3#203]
Trying to import a file with a column name containing a dash (`-`) results in an error: **Expected column header, got this instead: ...**. Currently the shared installation has at least one such column: `Phenotype/Intestinal/Gastro-Esophoegal_Reflux`.

**Comment by ifokkema** [comment]
A column name with a dash? That's really strange, because columns aren't allowed to have that character in them...
We need to then either allow it and change the parsing of the column header, or keep it like it is, investigate how this column got there, and rename it.

I don't remember why I didn't allow for a `-` in the name, I guess it's historic because using a hyphen will require the column to be quoted. But since we're quoting all custom columns anyway, we could allow it?

**Comment by mkroon1** [comment]
> or keep it like it is, investigate how this column got there, and rename it.

With superficial trying, I haven't been able to create a column with a hyphen in it. So my best guess is it was created in the DB directly and we should rename it.

**Comment by ifokkema** [comment]
Really strange, I have no clue how it got there! But your solution sounds good to me!

**Comment by mkroon1** [comment]
Renamed to `Intestinal/GastroEsophoegal_Reflux`.
