### ISSUE TITLE
Set config.ini.php through environment variables

### ISSUE THREAD

**Issue by Welliton309** [LOVDnl/LOVD3#226]
I am working on a Docker image for LOVD server and I would like to know if there is a way to set `config.ini.php` values (hostname, username, passsword) through environment variables.

I tried:

``` php
<?php exit(); ?>

[database]
driver = mysql
hostname = "${LOVD_DB_HOST}"
username = "${LOVD_DB_USER}"
password = "${LOVD_DB_PASSWORD}"
database = "${LOVD_DB_NAME}"
table_prefix = lovd
```

But it did not work. The server returned error "Error parsing config file: incorrect value for setting 'hostname' in section [database]". Any idea how to solve this problem?

**Comment by ifokkema** [comment]
Hi,

Ah, I see. The `config.ini.php` file is read as a text file and not interpreted, so that doesn't automatically resolve to the constant. How were the environment variables set? I suppose a `getenv('LOVD_DB_HOST', true);` would work? I guess there are two options here:

1. Have the script that sets the environment variables instead edit the `config.ini.php` file.
2. Add code to LOVD to read out the environment variables, if present.

Would the first option be an option for you?

**Comment by Welliton309** [comment]
Thank you @ifokkema for the answer. The environment variables are set at run time during creation of Docker container (I can see these variables in bash like `echo $LOVD_DB_HOST`). I think the second option is better for me.

Can you point the source code where I can edit to add the `getenv` calls?

Here is the [Docker image](https://hub.docker.com/r/welliton/lovd/) and the [source code](https://github.com/labbcb/docker-lovd) (I still need to add more information about your work in the README). Suggestions are very appreciate.

**Comment by mkroon1** [comment]
Hi, thanks for putting effort into this!

I'd like to add that using an external script to generate the config file from the environment settings is probably more future-proof than editing the source code. Maybe you could run something like [this](https://gist.github.com/mkroon1/5ca81094a55ae2aac68dabe2b30a93b6) from the dockerfile.

**Comment by ifokkema** [comment]
@mkroon1 I'm not sure to be honest - if we would update the LOVD config file, this script would need to be updated as well. Funny coincidence is actually that the script you link to is generating an old config file :wink:
Then again, @Welliton309 's current setup has the same limitation. I admit the config file is hardly touched, though, so this might not happen very much, yet I believe we can create a way here with very little code.

1. The Docker code could copy the `config.ini.php-lovd` file to `config.ini.php`. It would be a simple addition [here](https://github.com/labbcb/docker-lovd/blob/master/Dockerfile). This will satisfy LOVD's need for a config file to be present.
2. LOVD can easily be configured to assume empty values for a username, password and database field to be configured as an environment variable. PHP's `getenv()` will simply return false if the variable doesn't exist, so no harm done if it doesn't, and it won't allow an environment variable to overwrite the values configured in the `config.ini.php` file, since the values are only used as fallbacks if the config file is empty. I'm talking about [this code](https://github.com/LOVDnl/LOVD3/blob/6faa9096f1937789c1d989cbf8005b90e199fb78/src/inc-lib-init.php#L1028-L1039). Adding default values consisting of `getenv()` calls should suffice, like so:
```php
    'username' =>
        array(
            'required' => true,
            'default'  => getenv('LOVD_DB_USER', true),
        ),
````
@Welliton309 : Do you want to have a go at it? I don't mind sending you an updated `inc-lib-init.php`, but it's best for you to test, anyway :wink:

**Comment by ifokkema** [comment]
By the way.... I'm guessing it would help you a lot if we'd make a standard URL that would always download the latest LOVD, wouldn't it? Since your Dockerfile now needs to specify the version...

**Comment by Welliton309** [comment]
I tested the @mkroon1's solution and it working very well (see [Dockerfile ENTRYPOINT](https://github.com/labbcb/docker-lovd/blob/master/Dockerfile#L23)). It solved my problem. I will stay updated with future releases of LOVD. It would be great if LOVD support environment variable (however, I don't know which solution is the most secure).

I am using the LOVD 3.0-17 because my working group use this version. I will test the latest stable version and I will add a new tag for Docker image.

Thank you!

**Comment by ifokkema** [comment]
The alternative solutions discussed in this issue have been copied to #228 and #229. If you're interested to hear when they get implemented, please subscribe to these issues, thanks!
