### ISSUE TITLE
Working with custom columns

### ISSUE THREAD

**Issue by cbsolutions** [LOVDnl/LOVD3#230]
On the default tabs Genes, Transcripts, Variants, Individuals, Diseases, Screening  I have found the custom columns and need some guidance:
I added the custom Phenotype variables in the settings,  but to see the Phenotype data, I have to go to the Individuals tab and click on each individual at a time.  What I want is to see a list of the data in column mode.  Is there a way to add PHENOTYPE columns to the Individuals tab when I choose "View all individuals with variants in gene"?

**Comment by ifokkema** [comment]
Hi,

Since phenotype columns are configurable per disease, one LOVD instance may have hundreds of such columns (our shared LOVD3 instance has 250 active phenotype columns). Therefore, for gene-specific or system-wide views of individuals, showing the phenotype columns doesn't normally work well. When viewing such lists, LOVD doesn't yet know which phenotype entries are linked to the individuals that are to be shown, and can not select for the columns only active for those entries.

LOVD does however, have phenotype listings specific per disease; knowing the disease allows LOVD to pick the phenotype column configuration. You can find these lists by going to the disease you are interested in ("Diseases" tab -> Search for the disease you are interested in, and click on it) and then clicking on the link next to "Phenotype entries for this disease".

Does this help you?

**Comment by cbsolutions** [comment]
Thank you very much!  Appreciate it.  Will be able to work with this.
