### ISSUE TITLE
Wrong link for uncurated variants in drop-down menu Configuration area

### ISSUE THREAD

**Issue by mkroon1** [LOVDnl/LOVD3#26]
Copied from Trello:

> Data entries can have different statuses (see inc-init.php for the list, STATUS_* constants). See the manual (search for "statusid") for their explanations.
Marked is a bit special, because it's sometimes considered both Uncurated and Curated. It's public, but it's marked because the curator needs to do something with it still. In counts, Marked is considered curated (public), because otherwise the numbers would not add up.
The Configuration area has a variant information block on the left with numbers, and links. See the links and check how they work, by injecting search terms into the ViewList by setting a $_GET argument.
Now, the Configuration area tab's dropdown menu, has the option "View uncurated variants". "Uncurated" in this sense, means "Pending" (previously called "Submitted"), "Non public", or "Marked". As you may notice, the link in the dropdown menu doesn't work properly. It doesn't show all uncurated variants.

**Comment by mkroon1** [comment]
From what I understand, the link "View uncurated X variants" in the drop-down list under the configuration tab should point to a viewlist with all variants with any status of:

 * In progress
 * Pending
 * Non public
 * Marked

NB: "Pending" was not included previously.

Fixed in d69cea6d90f4b38bec021d7154fdfbdca5699fb7, this code has (as it did before) hard-coded status names which are also defined in the database. I could not avoid this without introducing an extra query for every pageview.

**Comment by mkroon1** [comment]
As mentioned in the issue description, the use of "uncurated" on the configuration page is ambiguous:

1. In the box on the left side of the page, "uncurated" excludes variants with status "marked".
2. In the drop-down under configuration, "uncurated" includes variants with status "marked".

I propose to rename the link in the drop-down to "View all variants for X that require attention", to cover both uncurated and marked variants.

@ifokkema, what are your thoughts on this?

**Comment by ifokkema** [comment]
> NB: "Pending" was not included previously.
Correct, its addition is what we were looking for, but "In progress" should be left out. See comment there ;)

> I could not avoid this without introducing an extra query for every pageview.
That's alright - this was the same before, and we never changed those values - ever.

About the ambiguity, you're right. Although Marked is referred to as curated and uncurated since LOVD1, I agree it would be an improvement if we rename that view. To keep the name short, the link could be called: "View GENE variants that require attention". That's also more in line with the link below. The page title doesn't need to change. We could, but then you'll need to parse the $_GET search terms and verify that the exact search is indeed all variants that require attention.

**Comment by mkroon1** [comment]
Created PR #28
