### ISSUE TITLE
Issues with browsers remembering user's username and password

### ISSUE THREAD

**Issue by mkroon1** [LOVDnl/LOVD3#27]
From Trello:

> Some people like to configure their browsers to remember their password when logging into LOVD. We can't stop them, and I guess we shouldn't, but this has annoying side effects that we should try to stop.
The browser is not the smartest thing and thinks that every form that has a password field, is a login form. As such, it injects the password in the password field (alright), but also tries to find a field to put the username in. The browser is stupid and injects the username in the last field that is used before the password field. This can be any field in LOVD, and as such we see user's usernames showing up in submissions all the time.
Devise a plan that would be simple to implement in LOVD, that would fix this problem. Examples: having LOVD add a hidden text field that does nothing (field's name is important) right before a password field, or perhaps field with display:none, or otherwise detect user's username in last field and automatically remove?

**Comment by mkroon1** [comment]
Reproduced with Firefox 44.0.2 (linux) on pages `users/userID?edit` and `settings?edit` where first password field is automatically filled and username is put in previous text field. Could not reproduce with Chromium 48 (linux).

Browser directive `autocomplete="off"` to avoid autofill behavior does not work in this case, as is explained [here](https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion).

Adding hidden username and password fields, as per [this suggestion](http://stackoverflow.com/a/23234498) fixes the issue for Firefox, but curiously introduces the issue in Chromium, where now the password field is automatically filled.

[This tip](http://stackoverflow.com/a/24247840), where we make the password field read-only until it captures focus, works for both Firefox and Chromium. Though this breaks forms for users with javascript disabled. But LOVD relies on javascript anyway.

**Comment by ifokkema** [comment]
Thanks! Does the last change also fix the issue in Firefox? So basically, because the browser can't fill in the password, it also doesn't fill in the username?
This fixes the issue for us, but might make users annoyed that we broke their password remembering feature.
Should we perhaps try to include that one text field before the password field, with display:none? Just one field, not two as shown in your second link. And it needs to be just before the password. I think that would not break the users's feature, while we do solve our issue with the username inserted into random fields.

**Comment by mkroon1** [comment]
> Does the last change also fix the issue in Firefox? So basically, because the browser can't fill in the password, it also doesn't fill in the username?

Yes, that's true. In my tests, this is the only way that fixes it for both browsers.

The way I implemented it right now makes it optional per form. The login form does not use inc-lib-form.php and so will not be affected.

**Comment by mkroon1** [comment]
New idea: I can make it a per-field setting. Where we can leave it off for password fields that require the current user's password. And a separate flag for putting a hidden text field just above the password field.

That means 2 extra flags for password fields in the form generator, but that shouldn't be much of a problem I think.

**Comment by ifokkema** [comment]
I think we can't just decide to block users from having their passwords remembered. We might do it after the Curate All feature has been implemented, but currently we require a curator to curate a new entry by going through all parts of the submission (Individual, Phenotype, Variants), which could be super annoying in case the password is not remembered. In principle, we can leave the code as is (with minor adjustments) to have this feature for later use, but before the Curate All feature has been enabled, I think we'd just annoy a big group of users.

> And a separate flag for putting a hidden text field just above the password field.

I think we can just always do that, since it will be in nobody's way if it's there but not needed. Makes the interfacing to lovd_viewForm() just a bit easier :) Since this should fix the problem of the usernames inserted, we'd be done for now, and we can start using the new code you wrote for blocking the browser from remembering the password after we implemented the Curate All feature.
