### ISSUE TITLE
Error inserting gene

### ISSUE THREAD

**Issue by crirocha** [LOVDnl/LOVD3#308]
I'm usung LOVD v.3.0 Build 20, and wen I try to inset the gene ELOA I receive a message saying:
"Failed to retrieve gene reference sequence. This could be a temporary error, but it is likely that this gene is not supported by LOVD."  
This gene was called TCEB3 and when I try to insert this name I have the message: "Entry TCEB3 is deprecated according to the HGNC, please use ELOA."

**Comment by ifokkema** [comment]
Hi,
Unfortunately, the systems that we use for various services are getting confused because they're using different gene symbols for this gene; both the old and the new one. How much control do you have over your LOVD instance - are you able to run an SQL file directly? We might be able to construct an SQL file that'll load ELOA and NM_003198.2 into your LOVD instance.

**Comment by crirocha** [comment]
I have root access to the mysql.


​

**Comment by ifokkema** [comment]
Sorry for the late reply. Please find attached an SQL file that will create the `ELOA` gene and the `NM_003198.2` transcript in an LOVD 3.0-17 database and up, configured for hg19. It will also enable the DNA, RNA and protein columns. If you want more columns for this gene, please add them manually. Please assign a curator to ELOA manually after running the SQL file.

[ELOA.sql.zip](https://github.com/LOVDnl/LOVD3/files/1466606/ELOA.sql.zip)
