### ISSUE TITLE
Transcript variant entry form: warning on empty *Genomic DNA change* unclear

### ISSUE THREAD

**Issue by mkroon1** [LOVDnl/LOVD3#39]
In the variant entry form (url ends with `variants/ID?edit`), the field *Genomic DNA change* is required. But when left empty, it's not highlighted after the form is submitted (though a warning is shown at the top of the page).

Additionally, such errors may be avoided in some cases when the content for *Genomic DNA change* is automatically generated from the field *DNA change* without having to manually click *Map to genome*. Is such behavior always appreciated, or does one in some cases override the value for *Genomic DNA change*?

**Comment by ifokkema** [comment]
Sometimes the value is overridden indeed (deletion or insertion into repetitive region, HGVS rule of describing change as 3' as possible && gene is on reverse), but also, when multiple transcripts are provided, we don't want to guess which one the user considers leading. I recommend we could add some warning message (either JS on submit of form, block submit; or PHP in errorAdd()) to use the mapping button(s) when one of the DNA fields is empty. Perhaps would be nice to have it in JS, because we can scroll there and/or highlight the button(s).
