### ISSUE TITLE
How to remove LOVD when the uninstall lock is set

### ISSUE THREAD

**Issue by peich69** [LOVDnl/LOVD3#394]
Hi there!!
How can I remove a local LOVD database?
When it was installed, the Uninstall box was checked so I can`t see the unistall link in setup menu.
I can't do it maually, because all gens and transcripts has been deleted, but has not been emptyed before, so I have a listl of  10k variants that should be removed manually.
I removed the LOVD directory in xampp\htdocs\ and unzipped a new one, but the data is still somewhere.
Any idea?
Thanks

**Comment by ifokkema** [comment]
Hi there!
Ah, I see. Yes, the variants are stored in the database, and removing the LOVD files will not remove them. There are a few things you can do:

- **Directly in MySQL**
Using the MySQL username and password, you can log into MySQL using `C:\xampp\mysql\bin\mysql.exe`, using the MySQL username and password that you've also configured in LOVD's `config.ini.php` file. There, you can remove the uninstall lock like:
`UPDATE lovd_config SET lock_uninstall = 0;`
Make sure you use the table prefix that you've configured in your `config.ini.php` file.
If it's also OK to just remove all the variants you have there instead of uninstalling, you can also do:
`DELETE FROM lovd_variants;`

- **Using phpMyAdmin**
XAMPP should come with a phpMyAdmin setup, which will allow you to work with the MySQL database using the webbrowser as a graphical interface. You can use that to remove the uninstall lock or empty the variants table like above, or you can just remove all LOVD tables (which is what the uninstaller does, anyway).

- **By just editing a text file** (if you just quickly want to start over)
If you just want to start over, and you don't really worry about having those 10K variants still somewhere, you can also just edit your `config.ini.php` file and choose a new table prefix. The LOVD code will then no longer see the previous LOVD tables, and will tell you LOVD is not installed. Then you can just install LOVD and start over. The variants from the previous installation will still be there, and you can change the table prefix in your `config.ini.php` file whenever you want to switch between LOVD data tables.

I hope this helps!

**Comment by peich69** [comment]
Thanks a lot!!
