### ISSUE TITLE
Graphical display links don't work

### ISSUE THREAD

**Issue by jbychang** [LOVDnl/LOVD3#435]
Hi folks,

Great work on the tool, it seems really useful. I’d like to visualize the mutations on the gene, and I think that you’ve coded in the links to do so (screenshot below), but the links don’t seem to work for me. 

![GetAttachmentThumbnail](https://user-images.githubusercontent.com/25805609/87707693-67c06b80-c756-11ea-9977-b06123bd2bba.png)

The underlying link to what I think is a .bed format file seems to work:

http://databases.lovd.nl/shared/api/rest/variants/NF1?format=text/bed

Do you know what might be going on?

Best,
Jeremy

**Comment by ifokkema** [comment]
Thank you for your report!

The UCSC shows a clear error that was helpful:
> Error line 2732 of http://databases.lovd.nl/shared/api/rest/variants/NF1?format=text/bed: chromEnd larger than chrom chr17 size (107844675 > 81195210)

There was an NF1 variant badly mismapped, and I corrected it. Now the BED file loads without problems in the UCSC browser:
[full view](http://genome.ucsc.edu/cgi-bin/hgTracks?clade=mammal&org=Human&db=hg19&position=chr17:29421895-29704745&hgt.customText=http%3A%2F%2Fdatabases.lovd.nl%2Fshared%2Fapi%2Frest%2Fvariants%2FNF1%3Fformat%3Dtext%2Fbed), [compact view](http://genome.ucsc.edu/cgi-bin/hgTracks?clade=mammal&org=Human&db=hg19&position=chr17:29421895-29704745&hgt.customText=http%3A%2F%2Fdatabases.lovd.nl%2Fshared%2Fapi%2Frest%2Fvariants%2FNF1%3Fformat%3Dtext%2Fbed%26visibility%3D4).

Thanks again, Jeremy!
Ivo

**Comment by jbychang** [comment]
Wow, that's really great, thank you so much Ivo!

**Comment by ifokkema** [comment]
Thanks, Jeremy! I've opened two new issues for this and I will investigate. Hopefully this week!
Cheers,
Ivo

**Comment by jbychang** [comment]
Thank you Ivo! I hope that it helps other genes in the database as well.

**Comment by ifokkema** [comment]
Hi Jeremy, I sort of managed to get the Ensembl links to work. Sort of, because loading a BED file into the Ensembl browser is an extremely buggy feature; hardly working and not well documented. You may need to remove all your Ensembl cookies for the links to work. You may need to load the link more than once before Ensembl decides to download and display the data. The compact view may not work. I haven't found a pattern to determine when it does, and when it doesn't work. It's not possible anymore for me to configure a track name, and Ensembl chooses to ignore the track's stored name. I'm afraid this is as good as it gets... :man_shrugging:

**Comment by ifokkema** [comment]
... and the NCBI sequence viewer works again! That one wasn't about the link, but about how it was accessing the link, so I had to update the BED file generator a bit. All done now, cheers!

**Comment by jbychang** [comment]
This is really great. thank you!
