### ISSUE TITLE
bulk import

### ISSUE THREAD

**Issue by summerghw** [LOVDnl/LOVD3#540]
**Is your feature request related to a problem? Please describe.**

Here is the thing, i need to import about 10,000 amount var to my instance, and i want to add about 100 columns  to interpretation the var(like the VEP output). If i add these columns one by one by hand it would be  miserable and frequency of errors will increased. And to import var, the import file size was limited (100MB ?). So i want to import var and new columns directly in mysql. 

**Describe the solution you'd like**

My plan:
1. first add columns in `lovd_columns` table 
2. add columns in `lovd_active_columns`
3. change the `/lovd/import.php`  to import biger file
4. use import format file to import var

problem:

1.after i changed `/lovd/import.php` script, `// Calculate maximum uploadable file size.
$nMaxSizeLOVD = (!LOVD_plus? 100000: 200000)*1024*1024; // 100MB LOVD limit, 250 MB for LOVD+.
$nMaxSize = min(
    $nMaxSizeLOVD,
    lovd_convertIniValueToBytes(ini_get('upload_max_filesize')),
    lovd_convertIniValueToBytes(ini_get('post_max_size')));`
it still up a error `There was a problem with the file transfer. Please try again. The file cannot be larger than`
I am not familiar with php, did i do it wrong ?

**Describe alternatives you've considered**

**Additional information**

**Comment by ifokkema** [comment]
You can import columns as well, and the limits you see are possibly because of your server settings. Let's see:

> Here is the thing, i need to import about 10,000 amount var to my instance, and i want to add about 100 columns to interpretation the var(like the VEP output).

Is the source indeed a VEP VCF file?


> If i add these columns one by one by hand it would be miserable and frequency of errors will increased. And to import var, the import file size was limited (100MB ?). So i want to import var and new columns directly in MySQL.

It's better to import the columns using the LOVD import format. Then you're sure the columns are configured in a way that will be compatible with LOVD.
*Activating* the columns is a different story. It's indeed not possible to activate sets of columns yet (you can create an issue for that if you want). So activating the columns is something you could do in MySQL.

File upload limits are also because of your server settings. On the import form, move your mouse over the blue question mark so you can see where the limits are.


> 1. first add columns in `lovd_columns` table

I would not recommend this, it's better to use an LOVD import for this.


> 2. add columns in `lovd_active_columns`

This would be necessary since we don't have a bulk-activate indeed.


> 3. change the `/lovd/import.php`  to import biger file

Check the import form to see what needs to be changed for this. What is the file size that you're trying to import? You also need to consider memory usage.

**Comment by summerghw** [comment]
> Check the import form to see what needs to be changed for this. What is the file size that you're trying to import? You also need to consider memory usage.

I tested the plan. As you said if i directly import columns to lovd by mysql, it will be some prolblem. the columns are only added in `lovd_columns` , `lovd_active_columns`, and I can see these columns in variant page, but in other pages like variants found section in screenings page, there was a error. It seems  these columns were not added in the `lovd_variant` table. So i will try to import columns by lovd_up_load_format_file.  Should the file  looks like this ?
![image](https://user-images.githubusercontent.com/39901746/129148863-aecf801c-db5f-4be8-a4b3-a4fc3c737494.png)

**Comment by summerghw** [comment]
> That won't work; like I said you can import the columns using the LOVD3 import format, but that's not for activating the columns. You'll need to activate columns directly in MySQL, or automate the LOVD interface using a tool like Selenium, or submit a bug report and wait until we implement it (this can take a while). Since you have already imported the columns in the `lovd_columns` table, using the LOVD3 import format is no longer useful.
> 
> The easiest thing to do now, if they're also already in `lovd_active_columns`, is to construct one large `ALTER TABLE` statement on the `lovd_variant` table to activate the columns.

thx.
