### ISSUE TITLE
Custom columns displayed in API retrieval call

### ISSUE THREAD

**Issue by angsm** [LOVDnl/LOVD3#592]
Hi all,

Could anyone enlightened me if there is an option to make a custom column's information appear on the API call for variant, or would I need to edit api.php itself? If anyone has a guide, it would be great.

Thank you!

**Comment by ifokkema** [comment]
Hi there, I assume you have your own local LOVD installation?
Since `/src/api.php` in general handles the old LOVD2-style API, I would recommend using the new GA4GH-style API. It's not yet documented, but on a fresh LOVD install, you can find it under `/src/api/ga4gh`. If not approached from a local IP address (127.0.0.1 or ::1), you'll need to send an `Authorization` header. See `/src/class/api.ga4gh.php`, lines 510 - 534.
The new API represents a lot more data, so perhaps the data you're looking for is already shared. Otherwise, you'll have to find or create a JSON equivalent to your custom column data. We use the VarioML JSON format, see [VarioML.org](https://VarioML.org).

**Comment by angsm** [comment]
Hi @ifokkema,
I did successfully access the json output from /src/api/ga4gh, thank you for the suggestion. 
Looked through the documentation for VarioML, looks like there is a definition template called LSBD.json, but it's not really found in the repository. 

May I know if I have a custom column added from the UI and the variable "interpretation" is now in mysql table **lovd_variants**. In theory, I just have to edit the variant.json file or as well as the api.ga4gh.php? I will proceed to read the code then.

Thank you.

**Comment by angsm** [comment]
Hi,
Just wanted to leave comments on the clinical interpretation of the variant. I just saw that there is a comment column that could be used and it shows up on the retrieval API. I think I will use that for the time being.

Thank you so much for the help, but will explore further into editing it.
