### ISSUE TITLE
LOVD 3 banner displays wrong gene symbol

### ISSUE THREAD

**Issue by leicray** [LOVDnl/LOVD3#602]
**Describe the bug**
The LOVD3 banner at the top of a page can (in some circumstances?) display the incorrect gene symbol relative to the variant that is being edited. The attached screenshot shows in the banner that the _COL1A1_ gene is being displayed, but the variant that is being edited is in the _COL3A1_ gene.

This bug is reminiscent of a similar bug in LOVD2 that I reported more than ten years ago

**To Reproduce**
I do not know how to reproduce this bug. The screenshot is taken from a shared Zoom screen for a user whom I was advising.

**Expected behaviour**
The gene symbol that is displayed in the banner at the top of the page ought to correspond with the gene that harbours the variant that is being edited.

**Screenshots**
![LOVD3_gene_confusion_issue](https://user-images.githubusercontent.com/10340330/171659851-afdbcd68-a69f-423c-bb07-286b181ca9e3.png)

**Your software (please complete the following information):**
 - Chrome Version 102.0.5005.63 (Official Build) (64-bit)
 - Version 3.0 Build 27

**Comment by ifokkema** [comment]
Thanks, Raymond! But this is not a bug.

The gene symbol on the top is meant as the last gene you've visited. It changes whenever gene-specific views are opened, e.g., the gene homepage, a gene's list of variants, the list of individuals with variants in a certain gene, etc. If you then continue to non-gene-specific views (like all genomic variants) or navigate by other means to variant entries (e.g., through individuals having variants in your gene of interest, but also having variants in other genes), you can reach specific variant entries located in genes other than the last visited one, without passing through gene-specific views of some other gene.

E.g., I select _BRCA1_. _BRCA1_ gets selected at the top of the gene. I view all _BRCA1_ variants and select a variant. Then navigate to the individual that harbors this variant. Then see this patient also has a variant in _BRCA2_. I click this variant. I'm now viewing a variant in _BRCA2_ while the header still lists _BRCA1_.

Also, there's the possibility that variants are mapped on multiple genes. You can switch between the different mappings of that variant, basically viewing all genes that this variant is mapped to. This doesn't reload the page, and therefore it's not possible at the moment to change the header at all.

However, the question is if it should. Since the viewer didn't get to this record through a gene-specific view of the gene harboring the variant in question, how will the software know the user is really interested in this gene? Perhaps next they'll simply wish to navigate back to the gene they were viewing originally? We'll make an assumption either way. The current assumption is simpler :wink:
