### ISSUE TITLE
Improve the presentation of genomic locations

### ISSUE THREAD

**Issue by leicray** [LOVDnl/LOVD3#610]
**Is your feature request related to a problem? Please describe.**
I think that the genomic location of sequence variants could be made more consistent. The presentational format for GRCh37 and GRCh38 is inconsistent and is potentially confusing for the novice user. For example, the "DNA changes" for the two genome builds is presented in two different ways:

![image](https://user-images.githubusercontent.com/10340330/185063863-97cea864-62f2-4019-8c28-da51c438d570.png)

**Describe the solution you'd like**
It would make sense to present both locations in the same format:

DNA change (genomic - relative to hg19 / GRCh37)
DNA change (genomic - relative to hg38 / GRCh38)

Corresponding changes ought to also be made to the edit interface which is perhaps even more confusing:

![image](https://user-images.githubusercontent.com/10340330/185065790-56eb03d8-b214-4364-a479-75a0d961e6fd.png)

**Additional information**
The described solution relates solely to the interface and would require no changes to the underlying database structure.

**Comment by ifokkema** [comment]
This issue is specific to the GV shared LOVD3 instance. The GV shared (i.e., Johan) "solved" storing hg38 coordinates by creating a custom column. Custom columns don't support having different headings for data listings and detailed data views, and a very long title doesn't work well on a data listing. The hg38 field is also not "special" in any way, and LOVD3 does not support mapping or variant validation on a custom column; as such, LOVD3 doesn't even know that's a DNA field.

This issue has been solved in LOVD3.5, more specifically, using #609. I don't have a timeline yet for the release of LOVD 3.5, but depending on how this autumn is going, we might make significant progress with a release coming out early next year.

**Comment by leicray** [comment]
Thank you for the explanation. I will patiently for LOVD 3.5 😊
