### ISSUE TITLE
uncorrect order of custom columns

### ISSUE THREAD

**Issue by riccardo74** [LOVDnl/LOVD3#70]
Hallo,
I have a local installation of LOVD 3.0 build 08.
I prepared a really detailed phenotype section. It comprises over 60 items. I tried to give them a precise order, but the field are visualized in an apparently random order. Filling in them unordered is really confusing. Is it a bug already fixed by the new rebuilds or upgrading would not help? Thanks

**Comment by ifokkema** [comment]
Hi there,
For Phenotype columns (just like VariantOnTranscript columns), there is a standard order for the custom columns (for new diseases / new genes) as well as an order specific for the object the column has been added to (a disease, in your case). My guess is that you changed the system-wide order, and not the object-specific order. For more information, see subsection "Changing the object-speciﬁc order of shared custom columns" in section "[Changing the order of custom columns](http://www.lovd.nl/3.0/docs/manual.html#pf31)" of the LOVD3 manual.

Furthermore, I'd like to note that since build 08, several important updates have taken place, of which one update was marked "Critical" because several parts of LOVD that relied on external services were no longer working because of changes to those services. I really recommend that you update your LOVD instance.

**Comment by riccardo74** [comment]
Thanks a lot. Yes , I solved following carefully the instructions of the manual. You have to reache the phenotype passing true the disease tab. SOLVED !!
I will upgrade to the last version quickly.
Thanks 
Riccardo

**Comment by ifokkema** [comment]
Excellent, good to hear! Have a nice weekend!
