### ISSUE TITLE
Let Selenium tests use test.mutalyzer.nl and not www.mutalyzer.nl

### ISSUE THREAD

**Issue by ifokkema** [LOVDnl/LOVD3#80]
Our Selenium tests should be using test.mutalyzer.nl, so that we pick up their errors soon enough. The latest Mutalyzer release, done today, has a broken webservice. See:
https://github.com/mutalyzer/mutalyzer/issues/393

We should have picked that up, if we would have been using test.mutalyzer.nl.

- [x] Let the installer test include the inc-init.php (see [the geneloader](https://github.com/LOVDnl/geneloader) for example code) and run a query to change the Mutalyzer URL to that of the test installation.

Also:
- [x] Put code for parsing INI file in a function in inc-lib-init.php.
- [x] Let the bootstrap script use that function, instead of duplicating the code.

**Comment by mkroon1** [comment]
I propose to put a query setting the configuration option in the database in [selenium_tests/phpunit_bootstrap.php](https://github.com/LOVDnl/LOVD3/blob/master/tests/selenium_tests/phpunit_bootstrap.php) because:

* It's a configuration in the database, which we shouldn't be able to override with settings from the configuration file.
* It's primarily used in the selenium tests, where it is difficult to mock the DB.
* As far as I can see, the mutalyzer url is not configurable at the moment via the configuration page or during installation.

**Comment by ifokkema** [comment]
Ah, good idea! But, how often is that bootstrap script run? Just once during testing, or before every test suite?
Because after every uninstall of LOVD, that query would need to be repeated...

If the bootstrap is run just once, then perhaps we should let it change the URL in the LOVD source, or we need to make the URL configurable...

**Comment by mkroon1** [comment]
You're right, the bootstrap script is only run at the very beginning.

I'm not a fan of changing the source code from the bootstrap script, so I would prefer to make the setting configurable and then configure it in the install_LOVD test (or in a separate test) which is run at the beginning of every test suite.

**Comment by ifokkema** [comment]
I've put the to-do tasks in the issue. If I missed something, let me know or feel free to add it :wink:
