### ISSUE TITLE
Misleading text "No transcripts or variants found"

### ISSUE THREAD

**Issue by mkroon1** [LOVDnl/LOVD3#89]
For genes with a transcript, but no underlying variants, clicking the _Variants_ tab shows an info box with the text "No transcripts or variants found for this gene.".

Example on shared database: [A1CF](http://databases.lovd.nl/shared/variants/A1CF)

**Comment by ifokkema** [comment]
It might be, that this message is generated from the VL itself. If so, it's difficult to improve the message, but the code that generates it actually could use some clean up. Otherwise, being more precise would mean an extra query. If it's really important to you, check if you could be more precise without running that query all the time - try to run it only when no variants are found, or try to modify the existing query.
